
import Head from 'next/head'
import React from 'react'
import classNames from 'classnames/bind'
import style from "./AboutUs.module.scss"
import 'animate.css';
import PageTitle from '../../components/PageTitle'
import { Carousel, Col, Image, Row } from 'antd'

const cx = classNames.bind(style)
export default function Aboutus() {
 
  return (
    <>
        <Head >
                <title>Fooce | About us</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/icon.png" />
        </Head>
        <PageTitle name="About us" />
        <div className={cx("about-us")}>
            <div className={cx("about-product")}>
                <Image src={require("../../assets/imgs/la-co.png").default.src} className={cx("about-product-img")} preview={false}/>
                <Row gutter={30} justify="center" className={cx("about-product-row")} >
                    <Col span={5} className="gutter-row" >
                        <div className={cx("product-wrap")} >
                            <div className={cx("product-item", "juice")}>
                                <div className={cx("product-title")}>Jump For Juice</div>
                            <div className={cx("product-description")}>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dui ante, consectetur non scelerisque.
                            </div>
                            </div>
                            <div className={cx("product-item", "juice")}>
                                <div className={cx("product-title")}>Smootheory</div>
                                <div className={cx("product-description")}>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dui ante, consectetur non scelerisque.
                                </div>
                            </div>
                            <div className={cx("product-item", "juice")}>
                                <div className={cx("product-title")}>Smoothie Dreams</div>
                                <div className={cx("product-description")}>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dui ante, consectetur non scelerisque.
                                </div>
                            </div>
                        </div>
                        
                    </Col>
                    <Col span={6} className="gutter-row">
                        <Image src={require("../../assets/imgs/about-us-juice.png").default.src} preview={false}/>
                    </Col>
                    <Col span={5} className="gutter-row">
                        <div className={cx("product-wrap")} >
                            <div className={cx("product-item", "food")}>
                                <div className={cx("product-title")}>The Joyful</div>
                                <div className={cx("product-description")}>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dui ante, consectetur non scelerisque.
                                </div>
                            </div>
                            <div className={cx("product-item", "food")}>
                                <div className={cx("product-title")}>Rainbow Smoothies</div>
                                <div className={cx("product-description")}>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dui ante, consectetur non scelerisque.
                                </div>
                            </div>
                            <div className={cx("product-item", "food")}>
                                <div className={cx("product-title")}>Frozen Fruit</div>
                                <div className={cx("product-description")}>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dui ante, consectetur non scelerisque.
                                </div>
                            </div>
                        </div>
                    </Col>
                </Row>
                
            </div>
            <div className={cx("about-logo")}>
                <Row gutter={16} style={{justifyContent: "space-between"}}>
                    <Col span={3} className={`gutter-row ${cx("about-logo-wrap")}`}>
                        <Image src={require("../../assets/imgs/organic-logo-1.png").default.src} preview={false} className={cx("logo-img")}/>
                    </Col>
                    <Col span={3} className={`gutter-row ${cx("about-logo-wrap")}`}>
                        <Image src={require("../../assets/imgs/fresh-1.png").default.src} preview={false} className={cx("logo-img")}/>
                    </Col>
                    <Col span={3} className={`gutter-row ${cx("about-logo-wrap")}`}>
                        <Image src={require("../../assets/imgs/delicious.png").default.src} preview={false} className={cx("logo-img")}/>
                    </Col>
                    <Col span={3} className={`gutter-row ${cx("about-logo-wrap")}`}>
                        <Image src={require("../../assets/imgs/fresh-2.png").default.src} preview={false} className={cx("logo-img")}/>
                    </Col>
                    <Col span={3} className={`gutter-row ${cx("about-logo-wrap")}`}>
                        <Image src={require("../../assets/imgs/organic-logo-2.png").default.src} preview={false} className={cx("logo-img")}/>
                    </Col>

                </Row>
                
            </div>
            <div className={cx("about-says")}>
                <Carousel  dotPosition='bottom' dots={true} autoplay>
                   <div>
                        <div className={cx("says-title")}>
                                They Say
                        </div>
                        <div className={cx("says-text")}>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse non mi non nisl pulvinar aliquet. Morbi aliquet tortor ac metus bibendum.
                        </div>
                        <div className={cx("says-author")}>
                                Anna Richardson
                        </div>
                        <div className={cx("says-job")}>
                                Smoothie lover
                        </div>
                    </div>
                    <div>
                        <div className={cx("says-title")}>
                                They Say
                        </div>
                        <div className={cx("says-text")}>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse non mi non nisl pulvinar aliquet. Morbi aliquet tortor ac metus bibendum.
                        </div>
                        <div className={cx("says-author")}>
                                Anna Richardson
                        </div>
                        <div className={cx("says-job")}>
                                Smoothie lover
                        </div>
                    </div>
                    <div>
                        <div className={cx("says-title")}>
                                They Say
                        </div>
                        <div className={cx("says-text")}>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse non mi non nisl pulvinar aliquet. Morbi aliquet tortor ac metus bibendum.                        </div>
                        <div className={cx("says-author")}>
                                Anna Richardson
                        </div>
                        <div className={cx("says-job")}>
                                Smoothie lover
                        </div>
                    </div>
                        
                </Carousel>
            </div>
        </div>
    </>
    
  )
}
