import Head from 'next/head'
import React from 'react'
import PageTitle from '../../components/PageTitle'


export default function Admin() {
  return (
    <>
      <Head >
            <title>Fooce | Admin</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
        </Head>
        <PageTitle name = "Admin" />
        <p style={{textAlign: 'center', padding: "40px 0"}}>Welcome to the admin site. Please select option on header</p>
    </>
  )
}
