
import React from 'react'
import PageTitle from '../../components/PageTitle'
import Head from 'next/head'
import MenuType from '../../components/Menu'
import image from '../../constant/img/image'
import { Col, Row, Tabs, TabsProps } from 'antd'
import classNames from 'classnames/bind'
import style from "./Gallery.module.scss"
import GalleryCard from '../../components/GalleryCard'

const cx = classNames.bind(style)
const items: TabsProps['items'] = [
  {
    key: '1',
    label: 'Phòng Khách',
    children: 
    <Row gutter={20} style={{margin: "20px 0"}}>
      <Col className={cx("gallery-item")} span={8}>
          <GalleryCard img="livingroom" author="2020, Trương Minh Lệ" name="Phòng Khách kiểu Bắc Âu"/>
      </Col>
      <Col className={cx("gallery-item")} span={8}>
          <GalleryCard img="livingroom" author="2020, Trương Minh Lệ" name="Phòng Khách kiểu Bắc Âu"/>
      </Col>
      <Col className={cx("gallery-item")} span={8}>
          <GalleryCard img="livingroom" author="2020, Trương Minh Lệ" name="Phòng Khách kiểu Bắc Âu"/>
      </Col>
    </Row>,
  },
  {
    key: '2',
    label: 'Phòng Ngủ',
    children: 
    <Row gutter={20} style={{margin: "20px 0"}}>
      <Col className={cx("gallery-item")} span={8}>
          <GalleryCard img="livingroom" author="2020, Trương Minh Lệ" name="Phòng Khách kiểu Bắc Âu"/>
      </Col>
      <Col className={cx("gallery-item")} span={8}>
          <GalleryCard img="livingroom" author="2020, Trương Minh Lệ" name="Phòng Khách kiểu Bắc Âu"/>
      </Col>
      <Col className={cx("gallery-item")} span={8}>
          <GalleryCard img="livingroom" author="2020, Trương Minh Lệ" name="Phòng Khách kiểu Bắc Âu"/>
      </Col>
    </Row>,
  },
  {
    key: '3',
    label: 'Phòng ăn',
    children: 
    <Row gutter={20} style={{margin: "20px 0"}}>
      <Col className={cx("gallery-item")} span={8}>
          <GalleryCard img="livingroom" author="2020, Trương Minh Lệ" name="Phòng Khách kiểu Bắc Âu"/>
      </Col>
      <Col className={cx("gallery-item")} span={8}>
          <GalleryCard img="livingroom" author="2020, Trương Minh Lệ" name="Phòng Khách kiểu Bắc Âu"/>
      </Col>
      <Col className={cx("gallery-item")} span={8}>
          <GalleryCard img="livingroom" author="2020, Trương Minh Lệ" name="Phòng Khách kiểu Bắc Âu"/>
      </Col>
    </Row>,
  },
  {
    key: '4',
    label: 'Văn phòng',
    children: 
    <Row gutter={20} style={{margin: "20px 0"}}>
      <Col className={cx("gallery-item")} span={8}>
          <GalleryCard img="livingroom" author="2020, Trương Minh Lệ" name="Phòng Khách kiểu Bắc Âu"/>
      </Col>
      <Col className={cx("gallery-item")} span={8}>
          <GalleryCard img="livingroom" author="2020, Trương Minh Lệ" name="Phòng Khách kiểu Bắc Âu"/>
      </Col>
      <Col className={cx("gallery-item")} span={8}>
          <GalleryCard img="livingroom" author="2020, Trương Minh Lệ" name="Phòng Khách kiểu Bắc Âu"/>
      </Col>
    </Row>,
  },
  {
    key: '5',
    label: 'Phòng tắm',
    children: 
    <Row gutter={20} style={{margin: "20px 0"}}>
      <Col className={cx("gallery-item")} span={8}>
          <GalleryCard img="livingroom" author="2020, Trương Minh Lệ" name="Phòng Khách kiểu Bắc Âu"/>
      </Col>
      <Col className={cx("gallery-item")} span={8}>
          <GalleryCard img="livingroom" author="2020, Trương Minh Lệ" name="Phòng Khách kiểu Bắc Âu"/>
      </Col>
      <Col className={cx("gallery-item")} span={8}>
          <GalleryCard img="livingroom" author="2020, Trương Minh Lệ" name="Phòng Khách kiểu Bắc Âu"/>
      </Col>
    </Row>,
  },
];
export default function Menu() {
  return (
    <>
    <Head>
        <title>Thiết kế</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
    </Head>
    <div >
        <PageTitle name= {"Thiết kế"} />
        <div className={cx("design")}>
            <Tabs defaultActiveKey="1" items={items} className={cx("tabs")} />
        </div>
        
    </div>
    </>
    
  )
}
